# Exercises Python KNTU

* Name: Mohammad Kargar-gazkoh
* EMail: mohammadkargargazkoh@gmail.com
* GitHub: https://github.com/mohammadkargar99

1. Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [1]:
import numpy as np
array5X5 = np.random.random((5,5))
print("5X5 array:\n",array5X5)
print('\n\nminimum_values = ',array5X5.min())
print('maximum_values = ',array5X5.max())


5X5 array:
 [[0.47257823 0.83216141 0.61129995 0.62803526 0.80909613]
 [0.82887455 0.74441735 0.99232125 0.49613811 0.81824957]
 [0.43337165 0.11186075 0.98739051 0.10944571 0.76094886]
 [0.40209988 0.75694419 0.49175311 0.82015481 0.59753995]
 [0.89182774 0.71569789 0.97527335 0.25952792 0.32413596]]


minimum_values =  0.10944570631288175
maximum_values =  0.992321248994124


2. Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable.

In [2]:
array10X4 = np.random.rand(10,4)
print("10X4 array:\n",array10X4,'\n\n')
store_array=array10X4[:5]
print("extract the first 5 rows of the array10X4 and store them into a store_array:\n",store_array)

10X4 array:
 [[0.95408887 0.74077779 0.66614071 0.50436438]
 [0.3416566  0.34998863 0.88115099 0.22210232]
 [0.14399322 0.27660488 0.18515503 0.1378745 ]
 [0.52891768 0.41160423 0.67661871 0.03803822]
 [0.32377631 0.44519036 0.03060165 0.43327658]
 [0.54015021 0.82810382 0.69425006 0.97034685]
 [0.03010723 0.51283446 0.63727149 0.99830246]
 [0.5769951  0.23818618 0.85019052 0.76022815]
 [0.84546348 0.15710687 0.5763426  0.51853404]
 [0.03294202 0.53435781 0.78866246 0.64225291]] 


extract the first 5 rows of the array10X4 and store them into a store_array:
 [[0.95408887 0.74077779 0.66614071 0.50436438]
 [0.3416566  0.34998863 0.88115099 0.22210232]
 [0.14399322 0.27660488 0.18515503 0.1378745 ]
 [0.52891768 0.41160423 0.67661871 0.03803822]
 [0.32377631 0.44519036 0.03060165 0.43327658]]


3. Write a NumPy program to create random vector of size 15 and replace the maximum value by -1.

In [3]:
random_vec = np.random.random(15)
print(f'random_vec:\n{random_vec}')
random_vec[random_vec.argmax()]=-1
print('\n\nreplace the maximum value of random_vec by -1:\n',random_vec)

random_vec:
[0.71767954 0.37033237 0.56161992 0.02525137 0.95023682 0.35936498
 0.45955295 0.12462518 0.78958709 0.31261098 0.4151095  0.22181071
 0.2768788  0.47728335 0.08770897]


replace the maximum value of random_vec by -1:
 [ 0.71767954  0.37033237  0.56161992  0.02525137 -1.          0.35936498
  0.45955295  0.12462518  0.78958709  0.31261098  0.4151095   0.22181071
  0.2768788   0.47728335  0.08770897]


4. normalize an array so the values range exactly between 0 and 1?

In [4]:
array = np.random.randint(0, 1000, (1, 100))
normalizedData = (array-np.min(array))/(np.max(array)-np.min(array))
print('array:\n',array)
print('\n\n\nnormalizedData:\n',normalizedData)

array:
 [[274 715 662 733 587 617 464 817 911 996 212 939 280 353 146 354 641 719
  240 226 712 555 194 305 244 173 300 554 932  99 481 552  45 518  44 443
   74 930  91 531 832 444 746 550 986 122 747  16 882 224 674 988 616 814
  320 805 627 832 961 717 469 700 984 143  87 979 108 324 881 308 199 524
  229 533 238 621 260 642 988 188 658 889 659 526 358 983 862 761 235 541
  803  87 233 381 250 586 220  31 221 271]]



normalizedData:
 [[0.26326531 0.71326531 0.65918367 0.73163265 0.58265306 0.61326531
  0.45714286 0.81734694 0.91326531 1.         0.2        0.94183673
  0.26938776 0.34387755 0.13265306 0.34489796 0.6377551  0.71734694
  0.22857143 0.21428571 0.71020408 0.55       0.18163265 0.29489796
  0.23265306 0.16020408 0.28979592 0.54897959 0.93469388 0.08469388
  0.4744898  0.54693878 0.02959184 0.5122449  0.02857143 0.43571429
  0.05918367 0.93265306 0.07653061 0.5255102  0.83265306 0.43673469
  0.74489796 0.54489796 0.98979592 0.10816327 0.74591837 0.
  0.88367347 0.2122449

5. convert an nd array of arrays into a flat 1d array

In [5]:
nd_array = np.array([[0, 1], [2, 3], [4, 5], [6, 7], [8, 9]])
print('nd_array:\n',nd_array)
# method 2
oned_array = nd_array.reshape(-1,)
# method 3
# 1d_array = nd_array.ravel()
print('\n\n1d_array:\n',oned_array)

nd_array:
 [[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]


1d_array:
 [0 1 2 3 4 5 6 7 8 9]


6. from 2010 to 2018 group weekdays and weekends in two lists

notes: you are allowed to just use datetime or numpy datetime

In [6]:
date_time_range = np.arange(np.datetime64('2010-01-04'), np.datetime64('2018-01-01'))

t = int(date_time_range.size/7)
date_time_range_new = date_time_range.reshape((t, 7))

weekdays = list(date_time_range_new)
weekends = list(date_time_range_new[:, 6])
print('weekdays of 2010 to 2018:\n',weekdays)
print('\n\n\n\nsweekends of 2010 to 2018:\n',weekends)

weekdays of 2010 to 2018:
 [array(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
       '2010-01-08', '2010-01-09', '2010-01-10'], dtype='datetime64[D]'), array(['2010-01-11', '2010-01-12', '2010-01-13', '2010-01-14',
       '2010-01-15', '2010-01-16', '2010-01-17'], dtype='datetime64[D]'), array(['2010-01-18', '2010-01-19', '2010-01-20', '2010-01-21',
       '2010-01-22', '2010-01-23', '2010-01-24'], dtype='datetime64[D]'), array(['2010-01-25', '2010-01-26', '2010-01-27', '2010-01-28',
       '2010-01-29', '2010-01-30', '2010-01-31'], dtype='datetime64[D]'), array(['2010-02-01', '2010-02-02', '2010-02-03', '2010-02-04',
       '2010-02-05', '2010-02-06', '2010-02-07'], dtype='datetime64[D]'), array(['2010-02-08', '2010-02-09', '2010-02-10', '2010-02-11',
       '2010-02-12', '2010-02-13', '2010-02-14'], dtype='datetime64[D]'), array(['2010-02-15', '2010-02-16', '2010-02-17', '2010-02-18',
       '2010-02-19', '2010-02-20', '2010-02-21'], dtype='datetime64[D]'), array(['2010-

7. Considering a four dimensions array, how to get sum over the last two axis at once?

In [8]:
fourDA = np.random.random((4, 5, 8, 2))

sum = fourDA.reshape(fourDA.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[6.31175696 9.63456895 7.19539918 8.59725325 8.71815215]
 [8.11437909 7.94918589 6.78493286 7.68595821 8.30331453]
 [8.04008195 8.09766071 6.94735392 8.94735567 7.57871224]
 [6.45176049 8.13106081 6.21118754 7.05377302 7.86818609]]


8. Consider 2 points p0, p1 describing a line (2d) and a point p, how to compute distance from p to this line?

In [9]:
def distance(p0, p1, p):
    T = p1 - p0
    L = (T**2).sum(axis=1)
    U = -((p0[:,0]-p[...,0])*T[:,0] + (p0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = p0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

p0 = np.random.uniform(-10, 10, (1, 2))
p1 = np.random.uniform(-10, 10, (1, 2))
p  = np.random.uniform(-10, 10, (1, 2))
print(distance(p0, p1, p))

[6.48358543]


:) thanks for checking out